sudo: required
services:
  - docker

env:
  - JAVA_VERSION=openjdk-8

script:
  - docker build -t fiji-$JAVA_VERSION fiji-$JAVA_VERSION
  - docker run --rm -v fiji-$JAVA_VERSION/macro.ijm:/opt/macro.ijm fiji-$JAVA_VERSION -macro /opt/macro.ijm test
